# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache pip downloads
cache:
    directories:
      - $HOME/.pip-cache/

language: python

python:
    - '2.7'

install:
    - pip install -e . --download-cache $HOME/.pip-cache

script:
    - py.test
