# Cache pip downloads
cache:
    directories:
      - $HOME/.pip-cache/

language: python

python:
    - '2.7'

before_install:
    - sudo apt-get install libxmlsec1-dev

install:
    - pip install -e . --download-cache $HOME/.pip-cache
    - pip install coveralls

script:
    - py.test --cov=soap_wsse --cov-report=term-missing

after_success: 
    - coveralls
