language: python

python:
    - '2.7'

before_install:
    - sudo apt-get update
    - sudo apt-get install libxmlsec1-dev
    - pip install codecov

install:
    - pip install -e .[test]

script:
    - py.test --cov=soap_wsse --cov-report=term-missing

after_success:
     - codecov
