language: python

python:
    - '2.7'

before_install:
    - sudo apt-get update
    - sudo apt-get install libxmlsec1-dev

install:
    - pip install -r test_requirements.pip -e .

script:
    - py.test --cov=soap_wsse --cov-report=term-missing

after_success: 
    - coveralls
